### Diplomado en Ciencia de Datos UNAM 
### Modulo 2: Matématica para ciencia de datos 
### Dr. Roberto Barcenas C. 
### Alumno: Ibarra Ramírez Sergio

#### Ejercico 1:  El participante identificará los principios fundamentales necesarios para la resolución de problemas del tema matemáticas para Ciencia de Datos.


##### Problema 1: 
Sean los vectores u = (4,-2,-1) , v= (-3, 1, 2) y el escalar k=-2 Calcular: <br> 

a) u +v  <br>
b) v + ku <br>
c) El producto interno (punto) uv <br>
d) La norma de los vectores u y v



##### a) u +v  

In [3]:
# importing libraries  
import numpy as np
import matplotlib.pyplot as plt
import math
  
u = np.array([4, -2, -1])
v = np.array([-3, 1, 2])

w = u + v 

print(f"El vector w = u+v es w:{w}")



El vector w = u+v es w:[ 1 -1  1]


##### b) v + ku <br>

In [6]:
u = np.array([4, -2, -1])
v = np.array([-3, 1, 2])

k = -2; 
p = v + (k*u) 

print(f"El vector p = v + ku es p:{p}")

El vector p = v + ku es p:[-11   5   4]


##### c) El producto interno (punto) uv <br>

In [7]:
k = np.dot(u,v)

print(f"El vector k = u v es k:{k}")

El vector k = u v es k:-16


##### d) La norma de los vectores u y v

In [8]:
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

print("La normal del vector u es:", norm_u)
print("La normal del vector v es:", norm_v)

La normal del vector u es: 4.58257569495584
La normal del vector v es: 3.7416573867739413


##### Problema 2: 
Sean las matrices  $A =\begin{bmatrix}
1 & 2 \\ 
-1  & 0
\end{bmatrix}$   y $B =\begin{bmatrix}
-2 & 9 \\ 
3  & 5
\end{bmatrix} $  Calcular: <br>

a) A + B  <br>
b) 2A  - B <br>
c) El producto AB <br>
d) La matriz transpuesta A


##### a) A + B  

In [27]:
import numpy as np
 
# input two matrices
A = ([1, 2],[-1 ,0 ])
B = ([-2, 9],[3 ,5 ])

 
C = [[0,0],
        [0,0]]
 

## Suma de matrices
# iterate through rows
for i in range(len(A)):  
# iterate through columns
    for j in range(len(A[0])):
        C[i][j] = A[i][j] + B[i][j]
 
for r in C:
    print(r)
 
 
# print resulted matrix
print(f"La matriz C = A + B es C:{C}")

[-1, 11]
[2, 5]
La matriz C = A + B es C:[[-1, 11], [2, 5]]


Otra manera más sencilla de hacerlo en Python sería: 

In [28]:
import numpy as np

A = np.array([[1, 2], [-1, 0]])
B = np.array([[-2, 9], [3, 5]])

C = A + B

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("La matriz C = A + B es:")
print(C)


Matrix A:
[[ 1  2]
 [-1  0]]
Matrix B:
[[-2  9]
 [ 3  5]]
La matriz C = A + B es:
[[-1 11]
 [ 2  5]]


##### b) 2A  - B 

In [20]:
k = -2
A2 = k * A
print(A2)



# This will return dot product
D = A2 -B
 
 
# print resulted matrix
print(f"La matriz D = A2 -B es D:{D}")
 

[[-2 -4]
 [ 2  0]]
La matriz D = A2 -B es D:[[  0 -13]
 [ -1  -5]]


##### c) El producto AB 

In [31]:

A = np.array([[1, 2], [-1, 0]])
B = np.array([[-2, 9], [3, 5]])

E = [[0 for x in range(len(A))] for y in range(len(B))]
 
# explicit for loops
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
 
            # resulted matrix
            E[i][j] += A[i][k] * B[k][j]
 
print(E)

[[4, 19], [2, -9]]


Otra manera más sencilla de hacerlo en Python sería: 

In [29]:
# This will return dot product
E = np.dot(A,B)
 
# print resulted matrix
print(f"La matriz E = A B es E:{E}")

La matriz E = A B es E:[[ 4 19]
 [ 2 -9]]


##### d) La matriz transpuesta A

In [33]:
A = np.array([[1, 2], [-1, 0]])

TraA = A.transpose()

# print resulted matrix
print(f"La matriz Transpuesta de A que es T es :{TraA}")

La matriz Transpuesta de A que es T es :[[ 1 -1]
 [ 2  0]]


##### Problema 3: 
Sean las matrices  

$ A = \begin{bmatrix}
3 & 1 & -1\\ 
6 & 1 & -2\\ 
4 &-3  & 2 
\end{bmatrix} $



Calcule su determinante

In [35]:
A_1 = np.array([[3, 1, -1], [6, 1, -2], [4, -3, 2]])


det_A_1 = np.linalg.det(A_1)

print(f"El determinante de la matgriz A_1 :{det_A_1}")

El determinante de la matgriz A_1 :-10.000000000000002


##### Problema 4:
 Determinar los siguientes limites  
 a ) $ \lim_{x->3}  x^{3}- 2x^{2} +8x-32 $ <br>
 b) $ \lim_{x->9} \frac{\sqrt{x}-3}{x-9} $

##### a ) $ \lim_{x->3}  x^{3}- 2x^{2} +8x-32 $ <br>

In [43]:
from sympy import Symbol, sqrt, limit

x = Symbol('x')
f1 = x**3 -2*x**2 + 8*x -32
limitx_3 = limit(f1, x, 3)
print(limitx_3)

1


 b) $ \lim_{x->9} \frac{\sqrt{x}-3}{x-9} $

In [41]:
from sympy import Symbol, sqrt, limit

x = Symbol('x')
f2 = (sqrt(x) - 3)/(x - 9)
limitx_9 = limit(f2, x, 9)
print(limitx_9)


1/6


In [36]:
# Define the function
def f(x):
    return x**3 - 2*x**2 + 8*x - 32

# Define the value of x and h
x = 3
h = 0.00001

# Calculate the value of the function at x+h and x-h
fxh = f(x + h)
fxhh = f(x - h)

# Use the formula for the numerical approximation of the derivative to estimate the limit value
limitx_3 = (fxh - fxhh) / (2*h)

print(limitx_3)


23.000000000195083
