#### <font color="#03997A"> Diplomado en Ciencia de datos UNAM </font>

##### <font color="#03997A"> Dr: Alejandro Pimentel </font>

##### <font color="#03997A"> Modulo 6 Aprendizaje de Maquina supervisado </font>

##### <font color="#03997A"> Practica 14 Clasificador Bayesiano (para datos de CHURN) Alumno: Ibarra Ramírez Sergio </font>

Vamos a importar la base de datos 

In [2]:
import pandas as pd

url_churn = "https://gitlab.com/dgtic5/res/-/raw/main/aprendizajeSupervizado/Churn_Modelling.csv"

tabla_churn = pd.read_csv(url_churn)
tabla_churn

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

Vamos a dividir en train y test además de aplicar OneHotEncoding 

In [3]:
y_churn = tabla_churn["Exited"]
X_churn = tabla_churn.drop(["Exited"],axis=1)
X_churn

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [4]:
from sklearn.model_selection import train_test_split

X_train_churn, X_test_churn, y_train_churn, y_test_churn = train_test_split(X_churn,y_churn,test_size=0.2,random_state = 2023)
y_test_churn

9595    0
4687    0
1963    0
4450    0
9238    0
       ..
6946    0
4939    1
9418    0
5247    0
6503    0
Name: Exited, Length: 2000, dtype: int64

Se separan las variables en categoricas y continuas 

- Variables categoricas

In [8]:
X_train_churn_categoricas = X_train_churn[['Geography', 'Gender', 'HasCrCard','IsActiveMember']] 
X_train_churn_categoricas

Geography  Gender  HasCrCard  IsActiveMember
2894    France    Male          1               1
149     France    Male          0               1
262     France  Female          1               0
555      Spain  Female          0               1
9147    France    Male          0               0
...        ...     ...        ...             ...
5852     Spain    Male          0               1
6049     Spain    Male          1               0
2743    France    Male          1               0
5657    France    Male          0               1
4951    France    Male          0               0

[8000 rows x 4 columns]

In [10]:
X_test_churn_categoricas = X_test_churn[['Geography', 'Gender', 'HasCrCard','IsActiveMember']] 
X_test_churn_categoricas

Geography  Gender  HasCrCard  IsActiveMember
9595    France    Male          1               1
4687    France    Male          0               1
1963   Germany    Male          1               0
4450    France    Male          1               1
9238    France  Female          1               0
...        ...     ...        ...             ...
6946    France    Male          1               1
4939    France    Male          0               0
9418     Spain  Female          1               1
5247    France    Male          1               1
6503   Germany  Female          0               1

[2000 rows x 4 columns]

- Variables continuas 

In [9]:
X_train_churn_continuas = X_train_churn[['CreditScore', 'Age', 'Tenure','NumOfProducts','EstimatedSalary']] 
X_train_churn_continuas

CreditScore  Age  Tenure  NumOfProducts  EstimatedSalary
2894          531   31       3              1         42589.33
149           416   32       0              2           878.87
262           557   32       6              2         14956.44
555           590   51       3              3        191932.27
9147          636   35       9              1        169286.74
...           ...  ...     ...            ...              ...
5852          544   22       3              1        110317.39
6049          592   41       0              2         65906.07
2743          689   22       4              1         51980.25
5657          496   30       0              1         27802.00
4951          658   20       7              2        187638.34

[8000 rows x 5 columns]

In [11]:
X_test_churn_continuas = X_test_churn[['CreditScore', 'Age', 'Tenure','NumOfProducts','EstimatedSalary']] 
X_test_churn_continuas

CreditScore  Age  Tenure  NumOfProducts  EstimatedSalary
9595          597   61       5              2         81299.17
4687          769   48       2              2        197885.72
1963          578   34       8              2         66680.77
4450          633   59       2              1        103159.11
9238          773   50       4              2        129372.94
...           ...  ...     ...            ...              ...
6946          418   36       7              1         69157.93
4939          616   37       5              2        154957.66
9418          639   27       2              1         82938.99
5247          633   59       5              1        137273.97
6503          455   37       6              1         54398.56

[2000 rows x 5 columns]

Se define y entrena el codificador OneHotEncoder para tratar con las variables categoricas

In [12]:
from sklearn.preprocessing import OneHotEncoder
codificador = OneHotEncoder()
codificador_churn_categoricas = codificador.fit(X_train_churn_categoricas)
codificador_churn_categoricas

OneHotEncoder()

Aplicamos el codificador 

In [13]:
#codificador.fit(X_train)
#X_train = codificador.transform(X_train)
X_train_churn_categoricas_codificadas = codificador_churn_categoricas.fit_transform(X_train_churn_categoricas)
X_train_churn_categoricas_codificadas

X_test_churn_categoricas_codificadas = codificador_churn_categoricas.fit_transform(X_test_churn_categoricas)
X_test_churn_categoricas_codificadas

<2000x9 sparse matrix of type '<class 'numpy.float64'>'
	with 8000 stored elements in Compressed Sparse Row format>

In [14]:
X_train_churn_categoricas_codificadas.toarray()

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [15]:
X_test_churn_categoricas_codificadas.toarray()

array([[1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 1., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.]])

##### Ahora si con los datos ya encodificados hacemos el modelo Naive Bayes de tipo MultinomialNB 

In [16]:
from sklearn.naive_bayes import MultinomialNB

modelo_NB_Multinomial_0 = MultinomialNB(alpha = 0)
modelo_NB_Multinomial_0.fit(X_train_churn_categoricas_codificadas,y_train_churn)

c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(


MultinomialNB(alpha=0)

In [17]:
y_pred_modelo_NB_Multinomial_0 = modelo_NB_Multinomial_0.predict(X_test_churn_categoricas_codificadas)
y_pred_modelo_NB_Multinomial_0

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

Evaluemos el primer modelo NB de clasificaicón de tipo MultinomialNB para vartiables categoricas en la clasificación de CHURN

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_test_churn,y_pred_modelo_NB_Multinomial_0))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1577
           1       0.00      0.00      0.00       423

    accuracy                           0.79      2000
   macro avg       0.39      0.50      0.44      2000
weighted avg       0.62      0.79      0.70      2000



c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_churn,y_pred_modelo_NB_Multinomial_0)

0.7885

In [27]:
from sklearn.metrics import precision_score

precision_score(y_test_churn,y_pred_modelo_NB_Multinomial_0)

c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.0

Veamos el comportamiento con un valor diferente de alpha para el suevizamiento 

In [19]:
from sklearn.naive_bayes import MultinomialNB

modelo_NB_Multinomial_1 = MultinomialNB(alpha = 1)
modelo_NB_Multinomial_1.fit(X_train_churn_categoricas_codificadas,y_train_churn)

y_pred_modelo_NB_Multinomial_1 = modelo_NB_Multinomial_1.predict(X_test_churn_categoricas_codificadas)
y_pred_modelo_NB_Multinomial_1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

Evaluemos el segundo modelo NB de clasificaicón

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test_churn,y_pred_modelo_NB_Multinomial_1))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1577
           1       0.00      0.00      0.00       423

    accuracy                           0.79      2000
   macro avg       0.39      0.50      0.44      2000
weighted avg       0.62      0.79      0.70      2000



c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

Y se puede obtener la probabilidad de pertenencia a cada clase 

In [21]:
modelo_NB_Multinomial_0.predict_proba(X_test_churn_categoricas_codificadas)

array([[0.91363921, 0.08636079],
       [0.90866976, 0.09133024],
       [0.66808037, 0.33191963],
       ...,
       [0.85922843, 0.14077157],
       [0.91363921, 0.08636079],
       [0.70026371, 0.29973629]])

En general se observa que el modelo modelo_NB_Multinomial (que solo tomó en cuenta variables categoricas) es bueno para evaluar /clasificar los clientes de tipo 1, peor NO los de tipo 0

#### En caso de usar GaussianNB para variables continuas continuas 

In [24]:
from sklearn.naive_bayes import GaussianNB


modelo_NB_Gaussian = GaussianNB()
modelo_NB_Gaussian.fit(X_train_churn_continuas,y_train_churn)

y_pred_modelo_NB_Gaussian = modelo_NB_Gaussian.predict(X_test_churn_continuas)
y_pred_modelo_NB_Gaussian

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

Evaluemos el modelo NB de clasificaicón de tipo GaussianNB para vartiables categoricas en la clasificación de CHURN

In [25]:
from sklearn.metrics import classification_report

print(classification_report(y_test_churn,y_pred_modelo_NB_Gaussian))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87      1577
           1       0.25      0.05      0.08       423

    accuracy                           0.77      2000
   macro avg       0.52      0.51      0.48      2000
weighted avg       0.68      0.77      0.70      2000



In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_churn,y_pred_modelo_NB_Gaussian)

0.768

In [29]:
from sklearn.metrics import precision_score

precision_score(y_test_churn,y_pred_modelo_NB_Gaussian)

0.25301204819277107

#### En general se muestra que el modelo de tipo GaussianNB de clasificación con variables independientes continuas es mejor que el MultinomialNB para la clasificación de dataset CHURN