#### <font color="#03997A"> Diplomado en Ciencia de datos UNAM </font>

##### <font color="#03997A"> Dr: Alejandro Pimentel  </font>

##### <font color="#03997A"> Modulo 8 Introducción al Deep Learning </font>

##### <font color="#03997A"> Ejercicio 4 CNN  Alumno: Ibarra Ramírez Sergio </font>

Se importan los datos de mnist_784 de numeros del 0 al 9 escritos a mano para su "reconocimieto" y clasificacion con una CNN 

In [6]:
import pandas as pd
review_hoteles = pd.read_csv("https://gitlab.com/dgtic5/res/-/raw/main/aprendizajeSupervizado/AHR.csv")
review_hoteles

Unnamed: 0                                 title  rating  \
0              0                   IMPOSIBLE DESCANSAR       2   
1              1          No es oro todo lo que reluce       3   
2              2        Un buen hotel con mucho ruido.       3   
3              3  SIN CALEFACCIÓN OPERATIVA Y CON FRÍO       2   
4              4             Deja bastante que desear.       2   
...          ...                                   ...     ...   
7610        7610       Muy buen hotel, recien abierto.       5   
7611        7611                             Excellent       5   
7612        7612                       Fantastic value       5   
7613        7613                             Excellent       5   
7614        7614                       Fantastic value       5   

                                            review_text  \
0     El fin de semana mi pareja y yo hicimos una re...   
1     El hotel en general está bien, las habtiacione...   
2     El hotel es moderno, amplio y limpio, pero no ...   
3     Calefacción averiada o no operativa. Se coment...   
4     Este hotel ha bajado notoriamente su categoria...   
...                                                 ...   
7610  Bastante cerca del centro de sevilla, servicio...   
7611  Séjour touristique à Séville, la découverte de...   
7612  Stayed here for 4 nights,  the room was big an...   
7613  Séjour touristique à Séville, la découverte de...   
7614  Stayed here for 4 nights,  the room was big an...   

                                   location                   hotel  label  
0     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      0  
1     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
2     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
3     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
4     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
...                                     ...                     ...    ...  
7610  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7611  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7612  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7613  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7614  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  

[7615 rows x 7 columns]

In [7]:
review_hoteles.dtypes

Unnamed: 0      int64
title          object
rating          int64
review_text    object
location       object
hotel          object
label           int64
dtype: object

In [7]:
# Print the column names
print(review_hoteles.columns)

Index(['Unnamed: 0', 'title', 'rating', 'review_text', 'location', 'hotel',
       'label'],
      dtype='object')


In [8]:
# Drop the 'Unnamed' column
review_hoteles = review_hoteles.drop(columns=['Unnamed: 0'])
review_hoteles

title  rating  \
0                      IMPOSIBLE DESCANSAR       2   
1             No es oro todo lo que reluce       3   
2           Un buen hotel con mucho ruido.       3   
3     SIN CALEFACCIÓN OPERATIVA Y CON FRÍO       2   
4                Deja bastante que desear.       2   
...                                    ...     ...   
7610       Muy buen hotel, recien abierto.       5   
7611                             Excellent       5   
7612                       Fantastic value       5   
7613                             Excellent       5   
7614                       Fantastic value       5   

                                            review_text  \
0     El fin de semana mi pareja y yo hicimos una re...   
1     El hotel en general está bien, las habtiacione...   
2     El hotel es moderno, amplio y limpio, pero no ...   
3     Calefacción averiada o no operativa. Se coment...   
4     Este hotel ha bajado notoriamente su categoria...   
...                                                 ...   
7610  Bastante cerca del centro de sevilla, servicio...   
7611  Séjour touristique à Séville, la découverte de...   
7612  Stayed here for 4 nights,  the room was big an...   
7613  Séjour touristique à Séville, la découverte de...   
7614  Stayed here for 4 nights,  the room was big an...   

                                   location                   hotel  label  
0     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      0  
1     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
2     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
3     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
4     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
...                                     ...                     ...    ...  
7610  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7611  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7612  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7613  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7614  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  

[7615 rows x 6 columns]

In [9]:
# Check for null values in each column
null_counts = review_hoteles.isnull().sum()
null_counts

title            0
rating           0
review_text      0
location       796
hotel          796
label            0
dtype: int64

## Predicción del rating usando el title

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [11]:
# Split data into features (titles) and target (ratings)
X_title = review_hoteles['title']
y_rating = review_hoteles['rating']

In [12]:
X_title

0                        IMPOSIBLE DESCANSAR
1               No es oro todo lo que reluce
2             Un buen hotel con mucho ruido.
3       SIN CALEFACCIÓN OPERATIVA Y CON FRÍO
4                  Deja bastante que desear.
                        ...                 
7610         Muy buen hotel, recien abierto.
7611                               Excellent
7612                         Fantastic value
7613                               Excellent
7614                         Fantastic value
Name: title, Length: 7615, dtype: object

Tokenizamos los valores de entrada a la red

In [13]:
# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_title)
X_title_sequences = tokenizer.texts_to_sequences(X_title)
X_title_sequences


[[165, 193],
 [5, 25, 592, 29, 18, 17, 670],
 [7, 23, 2, 12, 68, 108],
 [34, 880, 1809, 3, 12, 470],
 [267, 172, 17, 268],
 [132, 1, 1108],
 [40, 40, 3, 40],
 [1109, 593],
 [166],
 [1110, 519, 20, 471, 1810, 1, 2],
 [22, 1811],
 [14, 1812, 7, 881, 6, 9, 71, 1, 14],
 [5, 1813, 6, 11, 225],
 [24],
 [41, 1111, 17, 1814],
 [108, 882, 1, 1815],
 [29, 373, 416, 17, 333],
 [4, 69, 10, 18, 17, 25],
 [5, 232],
 [24, 243, 56],
 [40, 31],
 [43, 35, 38],
 [1816, 2, 883, 19, 188, 884],
 [1817, 671, 1818, 885, 3, 472],
 [93],
 [334, 19, 1112, 3, 291],
 [417, 374],
 [48],
 [9, 2, 90, 252, 473, 10, 39, 44, 17, 133, 26, 22, 1113],
 [672, 102],
 [84],
 [2, 12, 673, 3, 313, 520],
 [4, 279, 886, 594, 44, 27],
 [93],
 [5, 25, 7, 887],
 [16, 160, 5, 314, 39, 44, 27, 90, 177, 3, 32, 31, 20, 4, 94, 83],
 [5, 199, 1819],
 [30, 10, 146, 1, 194, 3, 21, 86],
 [52],
 [37, 16, 56],
 [76, 885, 76, 888],
 [96, 153, 5, 50, 210, 1820, 9, 674, 17, 133, 35, 100],
 [94, 2, 20, 375],
 [675, 1821, 1, 39, 676, 17, 57, 184, 1

Llevamos todos los vectore de input al mismo tamanio que el vector de mayor tamanio 

In [14]:
# Pad sequences
max_sequence_length = max([len(seq) for seq in X_title_sequences])
X_title_padded = pad_sequences(X_title_sequences, maxlen=max_sequence_length, padding='post')
X_title_padded

array([[165, 193,   0, ...,   0,   0,   0],
       [  5,  25, 592, ...,   0,   0,   0],
       [  7,  23,   2, ...,   0,   0,   0],
       ...,
       [878, 879,   0, ...,   0,   0,   0],
       [877,   0,   0, ...,   0,   0,   0],
       [878, 879,   0, ...,   0,   0,   0]])

In [15]:
X_title_padded.shape

(7615, 23)

Vamos a separar en train y test 

In [16]:
from sklearn.model_selection import train_test_split

X_title_padded_train, X_title_padded_test, y_ratin_train, y_ratin_test = train_test_split(X_title_padded,y_rating,test_size=0.2,random_state=2023)
X_title_padded_train

array([[102,   0,   0, ...,   0,   0,   0],
       [211,  60,  17, ...,   0,   0,   0],
       [147, 933, 416, ...,   0,   0,   0],
       ...,
       [103,   1,  77, ...,   0,   0,   0],
       [ 30,   0,   0, ...,   0,   0,   0],
       [ 18,  32, 104, ...,   0,   0,   0]])

In [17]:
X_title_padded_train.shape

(6092, 23)

Construccion de la RNN para la CLASIFICACIÓN DE RATING CON BASE EN TITLE

In [18]:
# Build the RNN model
model_RNN_title = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=128, input_length=max_sequence_length),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(5, activation='softmax')  # Assuming ratings are from 1 to 5
])
model_RNN_title


Se compila y se entrena el modelo para la clasificación de Ratings con base en title 

In [19]:
# Compile the model
model_RNN_title.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model_RNN_title.fit(X_title_padded_train, y_ratin_train - 1, epochs=10, batch_size=32, validation_split=0.2)  # Subtract 1 to convert 1-based ratings to 0-based index


Epoch 1/10
153/153 [==============================] - 7s 27ms/step - loss: 1.3468 - accuracy: 0.3417 - val_loss: 1.2225 - val_accuracy: 0.5316
Epoch 2/10
153/153 [==============================] - 3s 23ms/step - loss: 0.9712 - accuracy: 0.5723 - val_loss: 0.8698 - val_accuracy: 0.6481
Epoch 3/10
153/153 [==============================] - 4s 23ms/step - loss: 0.7320 - accuracy: 0.7014 - val_loss: 0.7284 - val_accuracy: 0.7047
Epoch 4/10
153/153 [==============================] - 3s 23ms/step - loss: 0.5724 - accuracy: 0.7708 - val_loss: 0.6981 - val_accuracy: 0.7301
Epoch 5/10
153/153 [==============================] - 3s 22ms/step - loss: 0.4921 - accuracy: 0.8075 - val_loss: 0.7441 - val_accuracy: 0.7276
Epoch 6/10
153/153 [==============================] - 3s 22ms/step - loss: 0.4328 - accuracy: 0.8348 - val_loss: 0.7339 - val_accuracy: 0.7449
Epoch 7/10
153/153 [==============================] - 3s 21ms/step - loss: 0.4025 - accuracy: 0.8537 - val_loss: 0.7276 - val_accuracy: 0.7482

Se evalua el modelo para la clasificación de Ratings con base en title 

In [20]:
# Evaluate the model
loss_modelo_RNN_title, accuracy_modelo_RNN_title = model_RNN_title.evaluate(X_title_padded_test, y_ratin_test - 1)
print("Accuracy:", accuracy_modelo_RNN_title)

48/48 [==============================] - 0s 7ms/step - loss: 0.9268 - accuracy: 0.7209
Accuracy: 0.7209454774856567


Ejemplo de predicicón con base en un título 

In [21]:
X_title_padded_test[0]

array([1652, 1653,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [22]:
# Reshape the input to have a batch dimension
X_sample_title = X_title_padded_test[5]  # Replace with the appropriate sample
X_sample_title_reshape = X_sample_title.reshape(1, -1)  # Reshape to (1, sequence_length)

# Predict using the reshaped input
prediction_model_RNN_title = model_RNN_title.predict(X_sample_title_reshape)
prediction_model_RNN_title

NameError: name 'X_sample' is not defined

In [ ]:
# Convert numerical sequence back to words
decoded_title_sample = tokenizer.sequences_to_texts([X_sample_title])[0]

print("Decoded title:", decoded_title_sample)


Decoded title: mal mal y mal


## Predicción del rating usando el review text 

Split data into features (review_text) and target (ratings)

In [9]:
# Split data into features (review_text) and target (ratings)
X_review = review_hoteles['review_text']
y_rating = review_hoteles['rating']
X_review

0       El fin de semana mi pareja y yo hicimos una re...
1       El hotel en general está bien, las habtiacione...
2       El hotel es moderno, amplio y limpio, pero no ...
3       Calefacción averiada o no operativa. Se coment...
4       Este hotel ha bajado notoriamente su categoria...
                              ...                        
7610    Bastante cerca del centro de sevilla, servicio...
7611    Séjour touristique à Séville, la découverte de...
7612    Stayed here for 4 nights,  the room was big an...
7613    Séjour touristique à Séville, la découverte de...
7614    Stayed here for 4 nights,  the room was big an...
Name: review_text, Length: 7615, dtype: object

Tokenizamos los valores de entrada a la red

In [10]:
# Tokenize the text
tokenizer_review = Tokenizer()
tokenizer_review.fit_on_texts(X_review)
X_review_sequences = tokenizer_review.texts_to_sequences(X_review)
X_review_sequences

[[5,
  159,
  1,
  161,
  42,
  261,
  3,
  107,
  594,
  14,
  162,
  6,
  36,
  15,
  12,
  5,
  159,
  1,
  326,
  3,
  3097,
  59,
  200,
  14,
  47,
  3,
  129,
  81,
  22,
  2691,
  7,
  9,
  2104,
  66,
  10483,
  19,
  15,
  64,
  22,
  348,
  4,
  39,
  75,
  16,
  326,
  46,
  4,
  2,
  152,
  1,
  232,
  39,
  10,
  14943,
  22,
  637,
  28,
  64,
  39,
  278,
  18,
  4,
  2799,
  3,
  1735,
  59,
  94,
  356,
  85,
  13,
  424,
  1,
  2,
  197,
  12,
  456,
  565,
  18,
  4,
  4902,
  4,
  274,
  109,
  8500,
  6,
  2,
  23,
  1,
  660,
  1,
  106,
  8,
  44,
  1002,
  5,
  15,
  1696,
  3,
  191,
  147,
  13,
  628,
  61,
  62,
  34,
  13,
  1886,
  4198,
  576,
  3,
  3098,
  3282,
  61,
  18,
  4,
  232,
  548,
  2692,
  200,
  353,
  16,
  326,
  1435,
  6,
  8,
  169,
  4,
  6082,
  33,
  6932,
  24,
  59,
  293,
  17,
  21,
  456,
  4903,
  17,
  389,
  8501],
 [5,
  15,
  6,
  210,
  35,
  28,
  13,
  14944,
  45,
  1064,
  3,
  5,
  29,
  11,
  10,
  73,
  1459,
  5

Llevamos todos los vectores de input al mismo tamanio que el vector de mayor tamanio

In [11]:
# Pad sequences
max_sequence_length_review = max([len(seq) for seq in X_review_sequences])
X_review_padded = pad_sequences(X_review_sequences, maxlen=max_sequence_length_review, padding='post')
X_review_padded

array([[   5,  159,    1, ...,    0,    0,    0],
       [   5,   15,    6, ...,    0,    0,    0],
       [   5,   15,   11, ...,    0,    0,    0],
       ...,
       [2492, 4399,  936, ...,    0,    0,    0],
       [4898, 8467, 1457, ...,    0,    0,    0],
       [2492, 4399,  936, ...,    0,    0,    0]])

In [12]:
max_sequence_length_review

1424

In [ ]:
X_review_padded.shape

(7615, 1424)

Vamos a separar en train y test

In [13]:
from sklearn.model_selection import train_test_split

X_review_padded_train, X_review_padded_test, y_rating_train, y_rating_test = train_test_split(X_review_padded,y_rating,test_size=0.2,random_state=2023)
X_review_padded_train

array([[510, 390, 116, ...,   0,   0,   0],
       [166, 143,   4, ...,   0,   0,   0],
       [646,  12,  42, ...,   0,   0,   0],
       ...,
       [ 22, 225,   9, ...,   0,   0,   0],
       [  1,  21, 379, ...,   0,   0,   0],
       [ 33,  83,  21, ...,   0,   0,   0]])

In [14]:
X_review_padded_train.shape

(6092, 1424)

Construccion de la RNN para la CLASIFICACIÓN DE RATING CON BASE EN REVIEW_TEXT

In [15]:
model_RNN_review2 = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer_review.word_index) + 1, output_dim=264, input_length=max_sequence_length_review),
    tf.keras.layers.LSTM(128, return_sequences=True),  # Add return_sequences=True
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(5, activation='softmax')  # Assuming ratings are from 1 to 5
])

Se compila y se entrena el modelo para la clasificación de Ratings con base en review

In [16]:
# Compile the model
model_RNN_review2.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Train the model
model_RNN_review2.fit(X_review_padded_train, y_rating_train - 1, epochs=10, batch_size=32, validation_split=0.2)  

Epoch 1/10
153/153 [==============================] - 738s 5s/step - loss: 1.3465 - accuracy: 0.3267 - val_loss: 1.3197 - val_accuracy: 0.3765
Epoch 2/10
153/153 [==============================] - 673s 4s/step - loss: 1.3292 - accuracy: 0.3433 - val_loss: 1.3151 - val_accuracy: 0.3765
Epoch 3/10
153/153 [==============================] - 676s 4s/step - loss: 1.3325 - accuracy: 0.3349 - val_loss: 1.3166 - val_accuracy: 0.3765
Epoch 4/10
153/153 [==============================] - 681s 4s/step - loss: 1.3269 - accuracy: 0.3411 - val_loss: 1.3185 - val_accuracy: 0.3765
Epoch 5/10
153/153 [==============================] - 677s 4s/step - loss: 1.3301 - accuracy: 0.3476 - val_loss: 1.3220 - val_accuracy: 0.2797
Epoch 6/10
153/153 [==============================] - 635s 4s/step - loss: 1.3263 - accuracy: 0.3427 - val_loss: 1.3194 - val_accuracy: 0.2797
Epoch 7/10
153/153 [==============================] - 619s 4s/step - loss: 1.3251 - accuracy: 0.3462 - val_loss: 1.3244 - val_accuracy: 0.2797

Se evalua el modelo para la clasificación de Ratings con base en review

In [17]:
# Evaluate the model
loss_modelo_RNN_review2, accuracy_modelo_RNN_review2 = model_RNN_review2.evaluate(X_review_padded_test, y_rating_test - 1)
print("Accuracy:", accuracy_modelo_RNN_review2)

48/48 [==============================] - 62s 1s/step - loss: 1.3554 - accuracy: 0.3355
Accuracy: 0.33552199602127075


Ejemplo de predicicón con base en un review

In [19]:
# Reshape the input to have a batch dimension
X_sample_review2 = X_review_padded_test[5]  # Replace with the appropriate sample
X_sample_review_reshape2 = X_sample_review2.reshape(1, -1)  # Reshape to (1, sequence_length)

# Predict using the reshaped input
prediction_model_RNN_review2 = model_RNN_review2.predict(X_sample_review_reshape2)
prediction_model_RNN_review2

1/1 [==============================] - 9s 9s/step


array([[2.2127047e-01, 1.1720824e-01, 3.2595554e-01, 9.7205077e-05,
        3.3546856e-01]], dtype=float32)

In [20]:
# Convert numerical sequence back to words
decoded_review_sample2 = tokenizer.sequences_to_texts([X_sample_review2])[0]

print("Decoded title:", decoded_review_sample2)

NameError: name 'tokenizer' is not defined