#### <font color="#03997A"> Diplomado en Ciencia de datos UNAM </font>

##### <font color="#03997A"> Dr: Alejandro Pimentel  </font>

##### <font color="#03997A"> Modulo 8 Introducción al Deep Learning </font>

##### <font color="#03997A"> Ejercicio 4 CNN  Alumno: Ibarra Ramírez Sergio </font>

Se importan los datos de mnist_784 de numeros del 0 al 9 escritos a mano para su "reconocimieto" y clasificacion con una CNN 

In [1]:
import pandas as pd
review_hoteles = pd.read_csv("https://gitlab.com/dgtic5/res/-/raw/main/aprendizajeSupervizado/AHR.csv")
review_hoteles

Unnamed: 0                                 title  rating  \
0              0                   IMPOSIBLE DESCANSAR       2   
1              1          No es oro todo lo que reluce       3   
2              2        Un buen hotel con mucho ruido.       3   
3              3  SIN CALEFACCIÓN OPERATIVA Y CON FRÍO       2   
4              4             Deja bastante que desear.       2   
...          ...                                   ...     ...   
7610        7610       Muy buen hotel, recien abierto.       5   
7611        7611                             Excellent       5   
7612        7612                       Fantastic value       5   
7613        7613                             Excellent       5   
7614        7614                       Fantastic value       5   

                                            review_text  \
0     El fin de semana mi pareja y yo hicimos una re...   
1     El hotel en general está bien, las habtiacione...   
2     El hotel es moderno, amplio y limpio, pero no ...   
3     Calefacción averiada o no operativa. Se coment...   
4     Este hotel ha bajado notoriamente su categoria...   
...                                                 ...   
7610  Bastante cerca del centro de sevilla, servicio...   
7611  Séjour touristique à Séville, la découverte de...   
7612  Stayed here for 4 nights,  the room was big an...   
7613  Séjour touristique à Séville, la découverte de...   
7614  Stayed here for 4 nights,  the room was big an...   

                                   location                   hotel  label  
0     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      0  
1     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
2     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
3     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
4     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
...                                     ...                     ...    ...  
7610  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7611  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7612  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7613  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7614  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  

[7615 rows x 7 columns]

In [2]:
review_hoteles.dtypes

Unnamed: 0      int64
title          object
rating          int64
review_text    object
location       object
hotel          object
label           int64
dtype: object

In [5]:
# Print the column names
print(review_hoteles.columns)

Index(['Unnamed: 0', 'title', 'rating', 'review_text', 'location', 'hotel',
       'label'],
      dtype='object')


In [7]:
# Drop the 'Unnamed' column
review_hoteles = review_hoteles.drop(columns=['Unnamed: 0'])
review_hoteles

title  rating  \
0                      IMPOSIBLE DESCANSAR       2   
1             No es oro todo lo que reluce       3   
2           Un buen hotel con mucho ruido.       3   
3     SIN CALEFACCIÓN OPERATIVA Y CON FRÍO       2   
4                Deja bastante que desear.       2   
...                                    ...     ...   
7610       Muy buen hotel, recien abierto.       5   
7611                             Excellent       5   
7612                       Fantastic value       5   
7613                             Excellent       5   
7614                       Fantastic value       5   

                                            review_text  \
0     El fin de semana mi pareja y yo hicimos una re...   
1     El hotel en general está bien, las habtiacione...   
2     El hotel es moderno, amplio y limpio, pero no ...   
3     Calefacción averiada o no operativa. Se coment...   
4     Este hotel ha bajado notoriamente su categoria...   
...                                                 ...   
7610  Bastante cerca del centro de sevilla, servicio...   
7611  Séjour touristique à Séville, la découverte de...   
7612  Stayed here for 4 nights,  the room was big an...   
7613  Séjour touristique à Séville, la découverte de...   
7614  Stayed here for 4 nights,  the room was big an...   

                                   location                   hotel  label  
0     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      0  
1     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
2     Seville_Province_of_Seville_Andalucia     Hotel_Rey_Alfonso_X      3  
3     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
4     Seville_Province_of_Seville_Andalucia           Melia_Sevilla      0  
...                                     ...                     ...    ...  
7610  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7611  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7612  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7613  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  
7614  Seville_Province_of_Seville_Andalucia  Eurostars_Guadalquivir      1  

[7615 rows x 6 columns]

In [8]:
# Check for null values in each column
null_counts = review_hoteles.isnull().sum()
null_counts

title            0
rating           0
review_text      0
location       796
hotel          796
label            0
dtype: int64

## Predicción del rating usando el title

In [12]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
# Split data into features (titles) and target (ratings)
X_title = review_hoteles['title']
y_rating = review_hoteles['rating']

In [10]:
X_title

0                        IMPOSIBLE DESCANSAR
1               No es oro todo lo que reluce
2             Un buen hotel con mucho ruido.
3       SIN CALEFACCIÓN OPERATIVA Y CON FRÍO
4                  Deja bastante que desear.
                        ...                 
7610         Muy buen hotel, recien abierto.
7611                               Excellent
7612                         Fantastic value
7613                               Excellent
7614                         Fantastic value
Name: title, Length: 7615, dtype: object

Tokenizamos los valores de entrada a la red

In [13]:
# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_title)
X_title_sequences = tokenizer.texts_to_sequences(X_title)
X_title_sequences


[[165, 193],
 [5, 25, 592, 29, 18, 17, 670],
 [7, 23, 2, 12, 68, 108],
 [34, 880, 1809, 3, 12, 470],
 [267, 172, 17, 268],
 [132, 1, 1108],
 [40, 40, 3, 40],
 [1109, 593],
 [166],
 [1110, 519, 20, 471, 1810, 1, 2],
 [22, 1811],
 [14, 1812, 7, 881, 6, 9, 71, 1, 14],
 [5, 1813, 6, 11, 225],
 [24],
 [41, 1111, 17, 1814],
 [108, 882, 1, 1815],
 [29, 373, 416, 17, 333],
 [4, 69, 10, 18, 17, 25],
 [5, 232],
 [24, 243, 56],
 [40, 31],
 [43, 35, 38],
 [1816, 2, 883, 19, 188, 884],
 [1817, 671, 1818, 885, 3, 472],
 [93],
 [334, 19, 1112, 3, 291],
 [417, 374],
 [48],
 [9, 2, 90, 252, 473, 10, 39, 44, 17, 133, 26, 22, 1113],
 [672, 102],
 [84],
 [2, 12, 673, 3, 313, 520],
 [4, 279, 886, 594, 44, 27],
 [93],
 [5, 25, 7, 887],
 [16, 160, 5, 314, 39, 44, 27, 90, 177, 3, 32, 31, 20, 4, 94, 83],
 [5, 199, 1819],
 [30, 10, 146, 1, 194, 3, 21, 86],
 [52],
 [37, 16, 56],
 [76, 885, 76, 888],
 [96, 153, 5, 50, 210, 1820, 9, 674, 17, 133, 35, 100],
 [94, 2, 20, 375],
 [675, 1821, 1, 39, 676, 17, 57, 184, 1

Llevamos todos los vectore de input al mismo tamanio que el vector de mayor tamanio 

In [14]:
# Pad sequences
max_sequence_length = max([len(seq) for seq in X_title_sequences])
X_title_padded = pad_sequences(X_title_sequences, maxlen=max_sequence_length, padding='post')
X_title_padded

array([[165, 193,   0, ...,   0,   0,   0],
       [  5,  25, 592, ...,   0,   0,   0],
       [  7,  23,   2, ...,   0,   0,   0],
       ...,
       [878, 879,   0, ...,   0,   0,   0],
       [877,   0,   0, ...,   0,   0,   0],
       [878, 879,   0, ...,   0,   0,   0]])

In [18]:
X_title_padded.shape

(7615, 23)

Vamos a separar en train y test 

In [16]:
from sklearn.model_selection import train_test_split

X_title_padded_train, X_title_padded_test, y_ratin_train, y_ratin_test = train_test_split(X_title_padded,y_rating,test_size=0.2,random_state=2023)
X_title_padded_train

array([[102,   0,   0, ...,   0,   0,   0],
       [211,  60,  17, ...,   0,   0,   0],
       [147, 933, 416, ...,   0,   0,   0],
       ...,
       [103,   1,  77, ...,   0,   0,   0],
       [ 30,   0,   0, ...,   0,   0,   0],
       [ 18,  32, 104, ...,   0,   0,   0]])

In [17]:
X_title_padded_train.shape

(6092, 23)

Construccion de la RNN para la CLASIFICACIÓN DE RATING CON BASE EN TITLE

In [20]:
# Build the RNN model
model_RNN_title = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=128, input_length=max_sequence_length),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(5, activation='softmax')  # Assuming ratings are from 1 to 5
])
model_RNN_title


Se compila y se entrena el modelo para la clasificación de Ratings con base en title 

In [22]:
# Compile the model
model_RNN_title.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model_RNN_title.fit(X_title_padded_train, y_ratin_train - 1, epochs=10, batch_size=32, validation_split=0.2)  # Subtract 1 to convert 1-based ratings to 0-based index


Epoch 1/10
153/153 [==============================] - 16s 44ms/step - loss: 1.2875 - accuracy: 0.3995 - val_loss: 0.9873 - val_accuracy: 0.5644
Epoch 2/10
153/153 [==============================] - 6s 41ms/step - loss: 0.8920 - accuracy: 0.6259 - val_loss: 0.8180 - val_accuracy: 0.6801
Epoch 3/10
153/153 [==============================] - 5s 35ms/step - loss: 0.7459 - accuracy: 0.7020 - val_loss: 0.7938 - val_accuracy: 0.6850
Epoch 4/10
153/153 [==============================] - 5s 32ms/step - loss: 0.6083 - accuracy: 0.7698 - val_loss: 0.7529 - val_accuracy: 0.7244
Epoch 5/10
153/153 [==============================] - 5s 34ms/step - loss: 0.5537 - accuracy: 0.7917 - val_loss: 0.7397 - val_accuracy: 0.7293
Epoch 6/10
153/153 [==============================] - 5s 34ms/step - loss: 0.4431 - accuracy: 0.8377 - val_loss: 0.7294 - val_accuracy: 0.7490
Epoch 7/10
153/153 [==============================] - 5s 32ms/step - loss: 0.4130 - accuracy: 0.8576 - val_loss: 0.7955 - val_accuracy: 0.740

Se evalua el modelo para la clasificación de Ratings con base en title 

In [24]:
# Evaluate the model
loss_modelo_RNN_title, accuracy_modelo_RNN_title = model_RNN_title.evaluate(X_title_padded_test, y_ratin_test - 1)
print("Accuracy:", accuracy_modelo_RNN_title)

48/48 [==============================] - 0s 8ms/step - loss: 0.8525 - accuracy: 0.7078
Accuracy: 0.7078135013580322


Ejemplo de predicicón con base en un títuo 

In [27]:
X_title_padded_test[0]

array([1652, 1653,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [37]:
# Reshape the input to have a batch dimension
X_sample_title = X_title_padded_test[5]  # Replace with the appropriate sample
X_sample_title = X_sample.reshape(1, -1)  # Reshape to (1, sequence_length)

# Predict using the reshaped input
prediction_model_RNN_title = model_RNN_title.predict(X_sample_title)
prediction_model_RNN_title

1/1 [==============================] - 0s 60ms/step


array([[8.8159782e-01, 6.6672176e-02, 5.1158287e-02, 1.4710568e-05,
        5.5703655e-04]], dtype=float32)

In [36]:
# Convert numerical sequence back to words
decoded_title_sample = tokenizer.sequences_to_texts([X_title_padded_test[5]])[0]

print("Decoded title:", decoded_title_sample)


Decoded title: mal mal y mal


## Predicción del rating usando el review text 