#### <font color="#03997A"> Diplomado en Ciencia de datos UNAM </font>

##### <font color="#03997A"> Dr: Eduardo Espinosa A. </font>

##### <font color="#03997A"> Modulo 7 Aprendizaje de Maquina NO supervisado </font>

##### <font color="#03997A"> Actividad Final
##### Alumno: Ibarra Ramírez Sergio </font>

Vamos a importar la data de Breastcancer 

In [29]:
from sklearn.datasets import load_breast_cancer

breast_cancer = load_breast_cancer()
breast_cancer


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
breast_cancer.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [30]:
X_breast_cancer = breast_cancer.data  # Features
X_breast_cancer


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [11]:
y_breast_cancer = breast_cancer.target  # Target variable
y_breast_cancer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

#### Gaussian Mixture Model implementado a data de breast_cancer

In [12]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components=2)  # Set the desired number of clusters
gmm_breast_cancer = gmm.fit(X_breast_cancer)
labels_gmm_breast_cancer = gmm_breast_cancer.predict(X_breast_cancer)
labels_gmm_breast_cancer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

Veamos que tal resutó nuestro modelo GMM para la clasificación de pacientes de breast_cancer 

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_breast_cancer,labels_gmm_breast_cancer)

0.9507908611599297

El 95% de los casos son clasificados correctamente usando GMM model para la data de breast_cancer

In [14]:
from sklearn.metrics import precision_score

precision_score(y_breast_cancer,labels_gmm_breast_cancer)

0.953168044077135

#### PCA  Model implementado a data de breast_cancer

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

Vamos a estandarizar las variables antes de aplivar el modelo PCA 

In [25]:
from tables import tests
from sklearn.model_selection import train_test_split


X_train_breast_cancer, X_test_breast_cancer, y_train_breast_cancer, y_test_breast_cancer = train_test_split(X_breast_cancer, y_breast_cancer, test_size=0.3)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  # Add parentheses to initialize the StandardScaler object


## Cuando uno ajusta el modelo se ajusta con los datos de entrenamienmt
X_train_breast_cancer_std = sc.fit_transform(X_train_breast_cancer)  # Pass X_train as an argument to fit_transform()

## Y para le prueba YA NO SE AJUSTE, SOLO SE TRANSFORMA
X_test_breast_cancer_std = sc.transform(X_test_breast_cancer)

X_train_breast_cancer_std

array([[-0.34858709, -0.72893575, -0.37604236, ..., -0.10056399,
         0.81722799,  0.7203713 ],
       [-0.36911462,  2.19384349, -0.403318  , ..., -0.7298559 ,
        -0.83218513, -0.6251055 ],
       [-0.38964215, -1.39958897, -0.45488602, ..., -1.11714817,
        -1.7959791 , -0.58086907],
       ...,
       [ 0.03557098, -0.24180587, -0.03168737, ..., -0.56939962,
        -0.40019598, -0.37577291],
       [ 0.64846439,  0.91824294,  0.72606407, ...,  1.74383228,
         3.18007773,  0.73760627],
       [ 2.22028673, -0.45025214,  2.08558438, ...,  1.08158262,
        -0.60637262, -1.05483079]])

Aplicamos el modelo PCA para reducir los componentes 

In [26]:
from sklearn.decomposition import PCA

## Se crea el objeto PCA defineidno el n_components con que 'nos quedaremos' 
pca = PCA(n_components=5)

## Se entrena el modelo PCA 

X_train_PCA_breast_cancer = pca.fit_transform(X_train_breast_cancer_std)


# Se hace la transformación / aplica el PCA ya entrenado para los X_test
X_test_PCA_breast_cancer = pca.transform(X_test_breast_cancer_std)


X_test_PCA_breast_cancer

array([[-5.90703951e-01,  1.92099168e+00,  1.40267306e+00,
         1.07945077e-01, -1.59317408e+00],
       [-4.12635836e+00, -1.32267589e+00,  8.74785669e-01,
         8.87026593e-02, -6.05539849e-01],
       [ 8.23215405e-01,  4.63569607e-01, -2.66664128e+00,
        -9.19233504e-01, -7.62634495e-02],
       [ 4.33817141e+00,  8.74231476e-01, -8.84701314e-01,
         3.07903945e-02, -5.46224397e-01],
       [ 6.66769612e+00, -1.74949750e+00,  7.47135264e-01,
        -1.56642160e+00,  3.00701739e-01],
       [ 6.30458771e+00, -6.89745873e-01, -1.74433950e-01,
        -8.74947313e-01, -9.09576666e-01],
       [ 3.90504817e-01,  2.26564829e+00,  5.59536029e-01,
         1.37512278e-01, -8.94117882e-02],
       [-4.64643801e+00, -7.07968190e-01,  1.23967773e-01,
         4.00223780e-01,  5.83519193e-01],
       [-1.25158070e+00, -1.79871715e+00,  5.44909939e-01,
        -1.76525868e+00, -8.81515062e-02],
       [ 4.49129119e+00, -5.15403968e+00, -4.63100692e-01,
        -6.79487694e-01

Ahora implementaremos un modelo de clasificación con las dimensiones más importantes

In [27]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components=2)  # Set the desired number of clusters
gmm_breast_cancer_con_PCA = gmm.fit(X_train_PCA_breast_cancer)
labels_gmm_breast_cancer_con_PCA = gmm_breast_cancer_con_PCA.predict(X_test_PCA_breast_cancer)
labels_gmm_breast_cancer_con_PCA

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

Veamos que tal resutó nuestro modelo GMM para la clasificación de pacientes de breast_cancer después de haber aplicado PCA 

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_breast_cancer,labels_gmm_breast_cancer_con_PCA)

0.19298245614035087

Se redujo drásticamente el accuracy de clasificación al reducir componentes 

#### IQR Model implementado a data de breast_cancer para detectar valores atipicos

In [31]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

# Load the Breast Cancer Wisconsin dataset
breast_cancer = load_breast_cancer()

# Extract the feature names
feature_names = breast_cancer.feature_names

# Create a DataFrame with the feature names and corresponding values
df_X_breast_cancer = pd.DataFrame(breast_cancer.data, columns=feature_names)

# Print the DataFrame
print(df_X_breast_cancer)


     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

Vamos a implementar el IQR model para detectar valores atipicos 

In [32]:
import numpy as np

# Create a dictionary to store the outliers for each feature
outliers_dict = {}

# Iterate over each feature name
for feature_name in df_X_breast_cancer.columns:
    # Get the values of the current feature
    data_feature = df_X_breast_cancer[feature_name]

    # Implement the Interquartile method to detect outliers
    def find_anomalies(data, cut=3):
        q25 = np.percentile(data, 25)
        q75 = np.percentile(data, 75)
        iqr = q75 - q25
        lower_limit = q25 - cut * iqr
        upper_limit = q75 + cut * iqr
        anomalies = [x for x in data if x < lower_limit or x > upper_limit]
        return anomalies

    # Detect outliers for the current feature
    outliers_feature = find_anomalies(data_feature)

    # Store the outliers in the dictionary
    outliers_dict[feature_name] = outliers_feature

# Print the dictionary of outliers for each feature
for feature_name, outliers_feature in outliers_dict.items():
    print(f"Outliers for {feature_name}: {outliers_feature}")


Outliers for mean radius: [28.11]
Outliers for mean texture: [39.28]
Outliers for mean perimeter: []
Outliers for mean area: [1878.0, 2250.0, 2499.0, 2010.0, 2501.0]
Outliers for mean smoothness: [0.1634]
Outliers for mean compactness: [0.3454]
Outliers for mean concavity: []
Outliers for mean concave points: []
Outliers for mean symmetry: [0.304]
Outliers for mean fractal dimension: [0.09744, 0.09296, 0.09502, 0.09575]
Outliers for radius error: [1.509, 1.296, 2.873, 1.292, 1.37, 2.547, 1.291]
Outliers for texture error: [3.568, 4.885, 3.647, 3.896]
Outliers for perimeter error: [11.07, 8.83, 8.649, 10.05, 9.807, 21.98, 10.12, 8.867, 9.424, 18.65, 9.635, 8.758]
Outliers for area error: [153.4, 134.8, 170.0, 233.0, 128.7, 525.6, 155.8, 137.9, 138.5, 199.7, 156.8, 133.0, 130.8, 164.1, 153.1, 224.1, 130.2, 176.5, 542.2, 180.2, 139.9, 158.7]
Outliers for smoothness error: [0.01721, 0.01835, 0.02333, 0.03113, 0.02075, 0.01736, 0.02177]
Outliers for compactness error: [0.1006, 0.09368, 0.09

#### KernelPCA Model implementado a data de breast_cancer para detectar valores atipicos

In [44]:
from sklearn.decomposition import KernelPCA

kpca_rbf = KernelPCA(n_components=2, kernel='rbf', gamma=0.1)  # Set the desired kernel and parameters



X_train_PCA_RBF_breast_cancer = kpca_rbf.fit_transform(X_train_breast_cancer_std)


# Se hace la transformación / aplica el PCA ya entrenado para los X_test
X_test_PCA_RBF_breast_cancer = kpca_rbf.transform(X_test_breast_cancer_std)


X_test_PCA_RBF_breast_cancer


array([[-0.06170496,  0.26515857],
       [ 0.33658793, -0.33866243],
       [-0.20129333,  0.2230182 ],
       [-0.37777813, -0.02690161],
       [-0.26394186, -0.07129009],
       [-0.32467162, -0.08591643],
       [-0.13357562,  0.30008327],
       [ 0.38202665, -0.29549999],
       [ 0.12244889, -0.23664182],
       [-0.2943852 , -0.09519811],
       [-0.21047856, -0.04979202],
       [ 0.41270803, -0.29932674],
       [ 0.34913599, -0.28267989],
       [ 0.03417483,  0.3549822 ],
       [-0.29074451, -0.0724418 ],
       [-0.15909041,  0.16755286],
       [ 0.03536092,  0.17285789],
       [-0.17519173,  0.00828445],
       [-0.2189678 , -0.03754929],
       [-0.25356211, -0.0023399 ],
       [-0.20123405, -0.04366078],
       [ 0.30016404,  0.28160734],
       [-0.2144683 , -0.03905751],
       [ 0.30718979, -0.51182429],
       [-0.21792799, -0.03955861],
       [ 0.1845054 , -0.07266553],
       [-0.0293543 ,  0.04134108],
       [-0.33743357, -0.11198527],
       [-0.23127641,

Vamos a usar el modeo GMM con la data de breast_cancer reducida con KernelPCA

In [45]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components=2)  # Set the desired number of clusters
gmm_breast_cancer_con_PCA_RBF = gmm.fit(X_train_PCA_RBF_breast_cancer)
labels_gmm_breast_cancer_con_PCA_RBF = gmm_breast_cancer_con_PCA_RBF.predict(X_test_PCA_RBF_breast_cancer)
labels_gmm_breast_cancer_con_PCA_RBF

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

Se observa como aplicando el KernelPCA mejoró muchisimo la clasificación que con el PCA normal 

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_breast_cancer,labels_gmm_breast_cancer_con_PCA_RBF)

0.847953216374269